### ISSUE TITLE
请问文件预览现在不能配置了吗

### ISSUE THREAD

**Issue by vuens** [steedos/steedos-project-template#10]
`public:
  webservices:
    pdfOnline:
      url: "http://oss.steedos.com/apps/pdfviewer-es5/web/viewer.html?rangeChunkSize=1024&file="
    officeOnline:
      url: "https://view.officeapps.live.com/op/view.aspx?src="`

放到docker-compose.yml文件里面就启动不起来了

> ERROR: The Compose file './docker-compose.yml' is invalid because:
'public' does not match any of the regexes: '^x-'
You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by chenzhipei** [comment]
配置文件发出来，目前这个项目已经作废了，新issue 在 https://github.com/steedos/steedos-platform/issues 这里报
